;;; Compiled snippets and support files for `org-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'org-mode
                     '(("__project.org" "#+TITLE:${1:Project Name}\n#+DATE:    `(format-time-string \"%Y-%m-%d\")`\n#+CONTACT: ${2:Contact name}\n\n$0\n\n* Tasks [/]\n* Timeframe\n* Notes" "__project.org" nil nil nil "/home/camus/.doom.d/templates/org-mode/__project.org" nil nil)
                       ("__invoice.org" "#+TITLE:${1:1234-5678}\n#+DATE:     `(format-time-string \"%Y-%m-%d\")`\n#+ISSUED:   ${2:`(format-time-string \"%Y-%m-%d\")`}\n#+PAID:     ${3:`(format-time-string \"%Y-%m-%d\")`}\n#+CURRENCY: ${4:CAD|USD|DKK|GBP}\n#+CONTACT:  ${5:Contact ID}\n#+PROJECT:  ${6:Project ID}\n\n| *Description*                                  | *qty* |   *rate* | *total* |\n|----------------------------------------------+-----+--------+-------|\n| $0 [1]                                         |     |        |       |\n|----------------------------------------------+-----+--------+-------|\n|                                              |     |        |       |\n#+TBLFM: $4=$2+$3::@>$4=vsum(@2..@-1)\n\n[1] ...\n\n* Comments\n...\n* Notes\n** Attachments [0/0]" "__invoice.org" nil nil nil "/home/camus/.doom.d/templates/org-mode/__invoice.org" nil nil)
                       ("__doom-readme" "#+TITLE:   ${1:`(if (string-match \"modules/\\\\([^/]+\\\\)/\\\\([^/]+\\\\)/.+\" buffer-file-name)\n                    (format \"%s/%s\"\n                            (match-string 1 buffer-file-name)\n                            (match-string 2 buffer-file-name))\n                  \"\")`}\n#+DATE:    `(format (format-time-string \"%B %%s, %Y\") (string-to-number (format-time-string \"%d\")))`\n#+SINCE:   ${2:<replace with next tagged release version>}\n#+STARTUP: inlineimages nofold\n\n* Table of Contents :TOC_3:noexport:\n\n* Description\n${3:# A summary of what this module does.}\n\n+ If possible, include a brief list of feature highlights here\n+ Like code completion, syntax checking or available snippets\n+ Include links to packages & external things where possible\n\n** Maintainers\n+ @username_linked_to_gihub (Author)\n+ @username_linked_to_gihub\n+ @username_linked_to_gihub\n\n# If this module has no maintainers, then...\nThis module has no dedicated maintainers.\n\n** Module Flags\n+ =+flag1= A short description of what this flag does and what it might need\n  when enabled.\n+ =+flag2= A short description of what this flag does and what it might need\n  when enabled.\n+ =+flag3= A short description of what this flag does and what it might need\n  when enabled.\n\n# If this module has no flags, then...\nThis module provides no flags.\n\n** Plugins\n# A list of linked plugins\n+ [[https://orgmode.org/][org-plus-contrib]]\n+ [[https://github.com/sabof/org-bullets][org-bullets]]\n+ [[https://github.com/TobiasZawada/org-yt][org-yt]]\n+ [[https://github.com/sebastiencs/company-box][company-box]]* (=+childframe=)\n+ =:lang crystal=\n  + [[https://github.com/brantou/ob-crystal][ob-crystal]]\n+ =:lang go=\n  + [[https://github.com/pope/ob-go][ob-go]]\n+ =+present=\n  + [[https://github.com/anler/centered-window-mode][centered-window]]\n  + [[https://github.com/takaxp/org-tree-slide][org-tree-slide]]\n  + [[https://gitlab.com/oer/org-re-reveal][org-re-reveal]]\n\n** Hacks\n# A list of internal modifications to included packages; omit if unneeded\n\n* Prerequisites\nThis module has no prerequisites.\n\n* Features\n# An in-depth list of features, how to use them, and their dependencies.\n\n* Configuration\n# How to configure this module, including common problems and how to address them.\n\n* Troubleshooting\n# Common issues and their solution, or places to look for help.\n$0" "Doom module readme" nil nil nil "/home/camus/.doom.d/templates/org-mode/__doom-readme" nil nil)
                       ("__contact.org" "#+TITLE:${1:Contact Name}\n#+DATE:     `(format-time-string \"%Y-%m-%d\")`\n#+EMAIL:    ${2:email@address.com}\n#+ADDRESS:  $3\n#+CITY:     $4\n#+COUNTRY:  $5\n\n${0:...}\n\n* Associates\n+ Associate's name :: associates@email.com\n* Projects [/]\n** ACTIVE ... [/]\n* Invoices [/]\n** PENDING YYMM-0000 *1,000 USD*\n* Notes\n* Correspondence" "__contact.org" nil nil nil "/home/camus/.doom.d/templates/org-mode/__contact.org" nil nil)
                       ("__" "#+TITLE: ${1:`\n(string-join\n (mapcar #'capitalize\n         ;; Replace -,_... with space\n         (split-string\n          (let (case-fold-search)\n            ;; Seperating lower from upper: hello|World\n            (replace-regexp-in-string\n             \"\\\\([[:lower:]]\\\\)\\\\([[:upper:]]\\\\)\" \"\\\\1 \\\\2\"\n             ;; Separating upper from (upper and lower): HTTP|Server\n             (replace-regexp-in-string \"\\\\([[:upper:]]\\\\)\\\\([[:upper:]][0-9[:lower:]]\\\\)\"\n                                       \"\\\\1 \\\\2\" (file-name-base buffer-file-name))))\n          \"[^[:word:]0-9]+\"\n          )) \" \" )\n`}\n\n$0" "Org template" nil nil nil "/home/camus/.doom.d/templates/org-mode/__" nil nil)))


;;; Do not edit! File generated at Fri Mar  3 16:50:57 2023
